### ISSUE TITLE
Can we replace MappingQGeneric by MappingQ?

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#151]
The deal.II docu https://www.dealii.org/developer/doxygen/deal.II/group__mapping.html#ga707ed00adeca71df2f3f44a102b53e3a says that `MappingQGeneric` is equivalent to `MappingQ`.

@kronbichler, @peterrum do you agree?

**Comment by peterrum** [comment]
Yes it is.

**Comment by kronbichler** [comment]
Yes, they are now equivalent, the change was made in July 2021 (after the release 9.3) in https://github.com/dealii/dealii/pull/12423 and https://github.com/dealii/dealii/pull/12561. If we replace it unconditionally, we introduce a possible problem when working with the 9.3 release because `MappingQ` (old version) produced wrong results for curved meshes, leaving gaps between the first layer of cells near the boundary (with genuine high order) and the all cells further inside the domain with only linear mapping. Still, I think it is right to make the change now as I do not think have many users yet with (a) curved grids and (b) still relying on the 9.3 release.

**Comment by nfehn** [comment]
ok, I am working on it currently.

We might also skip support for dealii-9.3 in ExaDG when the new dealii-10.0 release is there?

**Comment by kronbichler** [comment]
Yes, this is what I was thinking about, too.

**Comment by nfehn** [comment]
One test case indeed fails when using release dealii-9.3. Since we do not test automatically (or run the tests for both dealii-master and dealii-9.3), this should not be a problem. And as written above, we plan to skip support for dealii-9.3 in the near future.
