### ISSUE TITLE
Bug in InterfaceCoupling

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#165]
The setup function of `InterfaceCoupling` receives a map with boundary conditions for the dst-side (see `FSI::Driver::setup()`, but the code that fills the vector `marked_vertices` uses `map_bc` in the sense of `map_bc_src` (since the loop is peformed over the cells of `dof_handler_src.get_triangulation()`). 

I consider this a bug since the boundary IDs may be different for dst-side and src-side.

Since this part of the code is only relevant for performance, and only for version dealii-9.3 or older (for which we will skip support in the near future), I suggest to remove this part of the code.

@kronbichler @peterrum Please share your opinion on how to procede. It could realize it in PR #162 (which I am currently working on and which touches/refactors `InterfaceCoupling`).

Question @peterrum: Why is `marked_vertices` not used for newer dealii versions? Is the search of active cells with `RemotePointEvaluation` then at least as efficient as before using `marked_vertices`?

**Comment by nfehn** [comment]
I think I misunderstood the code. We need marked vertices for dealii > 10.0, right? So we have to fix this bug.

**Comment by peterrum** [comment]
The 10.0 path considers `marked_vertices`. The 9.3 path does not, since RPE did not accept such an argument; it was introduced in https://github.com/dealii/dealii/pull/13178 while my work on https://github.com/exadg/exadg/pull/126.

As far as I understand is `marked_vertices` making the finding of points faster and does not change the correctness of the algorithm. The logic how `marked_vertices` is determined was not modified in https://github.com/exadg/exadg/pull/126. 

> The setup function of InterfaceCoupling receives a map with boundary conditions for the dst-side (see FSI::Driver::setup(),

That should be src side.
