### ISSUE TITLE
Global coarsening multigrid does not give grid-independent iteration counts

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#313]
Iteration counts strongly increase for increasingly fine meshes.

The problem might be related to the multigrid transfer (in particular h-transfer) or how we construct the coarse triangulations for global coarsening MG.

**Comment by necioglu** [comment]
Here are the results I obtain using the Poisson/sine application. I used the parameters in master apart from the following:
- DegreeMin=DegreeMax=2, RefineMin=0 and RefineMax=7 in the input file.
- For the upper results, I didn't change anything regarding the multigrid strategy, i.e., local smoothing.
- For the lower results I used global coarsening multigrid: This means I activated the `create_coarse_triangulations`  and the `use_global_coarsening` variables. I used a distributed Triangulation in both cases, meaning that the following function is used for creating the coarse triangulations: `MGTransferGlobalCoarseningTools::create_geometric_coarsening_sequence`

@nfehn maybe you can change the title and remove Fullydistributed, since I observed these results with Distributed also. 

```
________________________________________________________________________________

Summary of results:

degree dofs           n_10    tau_10         throughput     
                              in s*core/DoF  in DoF/s/core  

2      36             9.8     5.77e-05       1.73e+04       
2      144            10.7    2.09e-05       4.78e+04       
2      576            10.7    1.05e-05       9.57e+04       
2      2304           10.8    7.11e-06       1.41e+05       
2      9216           10.7    6.29e-06       1.59e+05       
2      36864          10.7    5.80e-06       1.72e+05       
2      147456         10.7    5.63e-06       1.77e+05       
2      589824         10.8    5.59e-06       1.79e+05       
________________________________________________________________________________
```
```
________________________________________________________________________________

Summary of results:

degree dofs           n_10    tau_10         throughput     
                              in s*core/DoF  in DoF/s/core  

2      36             11.5    6.02e-05       1.66e+04       
2      144            12.9    2.36e-05       4.25e+04       
2      576            13.0    1.21e-05       8.24e+04       
2      2304           12.8    8.14e-06       1.23e+05       
2      9216           15.0    8.70e-06       1.15e+05       
2      36864          17.3    9.16e-06       1.09e+05       
2      147456         20.5    1.04e-05       9.65e+04       
2      589824         25.9    1.30e-05       7.72e+04       
________________________________________________________________________________
```

**Comment by nfehn** [comment]
I am pretty sure this has worked correctly at some point in the past at least for `p:d:T`. So we probably must have introduced a bug somewhere.

**Comment by necioglu** [comment]
I suspected this part of the code
https://github.com/exadg/exadg/blob/827c7a45b1d1f91718810872293aa7e240ee2b6b/include/exadg/grid/grid.cpp#L102-L113
and replaced it with:
```
    triangulation = std::make_shared<dealii::parallel::distributed::Triangulation<dim>>(
      mpi_comm,
      dealii::Triangulation<dim>::none,
      dealii::parallel::distributed::Triangulation<dim>::construct_multigrid_hierarchy);
```
Nothing changed.

**Comment by peterrum** [comment]
This is odd. 

> I am pretty sure this has worked correctly at some point in the past at least for p:d:T. So we probably must have introduced a bug somewhere.

Yes it used to work. I haven't worked on the global-coarsening algorithms in deal.II for the last 3/4 year; so I don't think the issue comes from there. @necioglu Could you try out a version of ExaDG before your first commits so that we can rule out that the restructuring in the grid class lead to unwanted side effects.

We should also use this occasion to enable the tests on GitHub so that we can catch such issues right away.

**Comment by necioglu** [comment]
I checked the master in multiple positions. After the PR #269 is merged in commit 80eb9334d4d22f3a29b569b1e4b8117fd132118, the iteration counts for global coarsening increase with increasing number of dofs. (see bellow) **I didn't check each commit introduced with the PR, I can do that if necessary.**
```
________________________________________________________________________________

Summary of results:

degree dofs           n_10    tau_10         throughput     
                              in s*core/DoF  in DoF/s/core  

2      36             11.5    6.31e-05       1.58e+04       
2      144            12.9    2.51e-05       3.98e+04       
2      576            13.0    1.27e-05       7.85e+04       
2      2304           12.8    8.52e-06       1.17e+05       
2      9216           15.0    9.35e-06       1.07e+05       
2      36864          17.3    9.80e-06       1.02e+05       
2      147456         20.5    1.15e-05       8.73e+04       
2      589824         25.9    1.76e-05       5.67e+04       
________________________________________________________________________________
```
In the commit 5d109b42b59b5f8ebdaaf050397f9ce18f0dd3d0, which is the PR merge before the above one, everything is fine. (see bellow)
```
________________________________________________________________________________

Summary of results:

degree dofs           n_10    tau_10         throughput     
                              in s*core/DoF  in DoF/s/core  

2      36             11.5    9.22e-05       1.09e+04       
2      144            12.9    2.33e-05       4.30e+04       
2      576            13.0    1.20e-05       8.36e+04       
2      2304           12.7    8.25e-06       1.21e+05       
2      9216           12.5    7.54e-06       1.33e+05       
2      36864          12.4    7.02e-06       1.42e+05       
2      147456         12.3    6.93e-06       1.44e+05       
2      589824         12.2    6.80e-06       1.47e+05       
________________________________________________________________________________
```

Important notes to mention:

1. With #269 the variable `create_coarse_triangulations` is introduced and the grid class must be used for triangulation creation, if one wants to create the coarse triangulations for global coarsening multigrid. There are also other changes to the multigrid structure.
2. I have always used the most up-to-date version of dealii, while investigating this. But since @peterrum mentioned he didn't do any changes to global coarsening, I didn't suspect there would be a mismatch situation between exadg and dealii.

**Comment by peterrum** [comment]
> I didn't check each commit introduced with the PR, I can do that if necessary.

@necioglu That would be great. It is a big PR. Once you have identified the commit, I'll take a more detailed look.

**Comment by necioglu** [comment]
> > I didn't check each commit introduced with the PR, I can do that if necessary.
> 
> @necioglu That would be great. It is a big PR. Once you have identified the commit, I'll take a more detailed look.

@peterrum Will do that later today.

**Comment by nfehn** [comment]
see also https://github.com/exadg/exadg/pull/295/files#r1088007190

**Comment by nfehn** [comment]
it does not seem to be a bug in the multigrid implementation, but rather a design problem, see issue #319.
