### ISSUE TITLE
ExaDG::MultigridPreconditionerBase calls distribute_mg_dofs() in case no h-multigrid is involved

### ISSUE THREAD

**Issue by gilrrei** [exadg/exadg#339]
ElementType::Hypercube, MultigridVariant::LocalSmoothing and MultigridType::cpMG causes the error message
```
An error occurred in line <2268> of file </home/rei/exa/dealii/source/dofs/dof_handler.cc> in function
    void dealii::DoFHandler<dim, spacedim>::distribute_mg_dofs() [with int dim = 3; int spacedim = 3]
The violated condition was: 
    ((this->tria->get_mesh_smoothing() & Triangulation<dim, spacedim>::limit_level_difference_at_vertices) != Triangulation<dim, spacedim>::none)
Additional information: 
    The mesh smoothing requirement 'limit_level_difference_at_vertices'
    has to be set for using multigrid!
```

**Comment by nfehn** [comment]
In `MultigridPreconditionerBase::do_initialize_dof_handler_and_constraints()`, we could write
```
      if(this->data.involves_h_transfer)
      {
        dof_handler->distribute_mg_dofs();
      }
```
in order to overcome the above error message. However, this does not solve the problem, and a segmentation-fault occurs a few lines later. The problem is that the `MultigridVariant::LocalSmoothing` path always wants to initialize `MGConstrainedDoFs`, no matter whether h-MG is involved or not. The code becomes unmanagable for me (and my constrained-dofs skills) from this point on ...

I don't know how to resolve this problem apart from reverting some of the changes from PR #331.
