### ISSUE TITLE
Handling of constrained dofs in matrix-free and iterative solvers

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#383]
The `vmult()` function in `OperatorBase` (applying the homogeneous operator) sets constrained dofs to zero before evaluating the actual matrix-vector product (in a matrix-free fashion), see https://github.com/exadg/exadg/blob/41f8752a19a667b64009fcd6f4325a087afe8baa/include/exadg/operators/operator_base.cpp#L282-L304

but the matrix free loops use `gather_evaluate()`, a combination of `read_dof_values()` and `evaluate()`, see https://github.com/exadg/exadg/blob/41f8752a19a667b64009fcd6f4325a087afe8baa/include/exadg/operators/operator_base.cpp#L1027-L1045

 The function `read_dof_values()` should actually use the constrained dofs passed to matrix-free via `AffineConstraints` (in contrast to `read_dof_values_plain()`), so there would be no need to set constrained dofs to zero in the src-vector in my opinion.
 
 For these reasons, I believe the current implementation is somewhat unclear or non-unique in terms of how to impose constraints for continuous Galerkin. I see two solutions to make the implementation clear or unique:

1. set constrained dofs to zero before `vmult()`, but then use `read_dof_values_plain()`.  Then, we can probably no longer write `gather_evaluate()`?
2. skip setting constrained dofs to zero before `vmult()`, and use `gather_evaluate()` (internally using `read_dof_values()`) as is done currently in `OperatorBase`. Further, add a comment to https://github.com/exadg/exadg/blob/41f8752a19a667b64009fcd6f4325a087afe8baa/include/exadg/poisson/spatial_discretization/operator.cpp#L147 and emphasize that `make_zero_boundary_constraints()` is essential, i.e. calling `interpolate_boundary_values()` for a problem with inhomogeneous boundary conditions would lead to wrong results (because `read_dofs_values()` uses these inhomogeneous boundary values, but we would actually need the homogeneous operator in `vmult()`).

@kronbichler @peterrum Do you agree? I would tend to realize option 2 since this simplifies the implementation in ExaDG and we should be able to just remove some lines of code in `OperatorBase` (making clear how contraints are applied in ExaDG and removing the ambiguity we have currently according to my understanding). Any concerns e.g. regarding performance?

**Comment by kronbichler** [comment]
I agree with option 2. The reason why we have option 1 is likely a leftover of some old continuous FEM code that implemented the edge constraints of local-smoothing multigrid with this code and then switched to the other option.

In general, the second option should also offer better performance, because we do not touch the data twice. We should overall aim to work towards better performance in the extraction of indices, see also https://github.com/dealii/dealii/pull/14324

A downside with imposing the constraints inside the operator is that we need the `read_dof_values_plain()` for handling the case of different constraints, e.g., the homogeneous constraints inside a matrix-vector product versus inhomogeneous (affine) constraints for residuals or similar setups. It would be nice if these could be somehow treated in one go.

> set constrained dofs to zero before `vmult()`, but then use `read_dof_values_plain()`.

That would not be enough. `read_dof_values` also applies hanging node constraints on adaptively refined meshes, whereas `read_dof_values_plain` does not. I admit that this design is not entirely clear inside `MatrixFree`, mostly due to the different requirements of different types of constraints (hanging nodes, periodicity, boundary conditions), see also the discussion on how different requirements interact in a non-trivial way through the discussion in https://github.com/dealii/dealii/issues/2000 (part on "Option to not assign and carry constrained degrees of freedom at hanging nodes and periodic boundaries" and following replies).

**Comment by nfehn** [comment]
Thanks for your explanations, @kronbichler.

If I understand you correctly, code currently using `read_dof_values_plain()` (I think we have this at several places in ExaDG) would not work in case of adaptively refined meshes with hanging nodes for continuous Galerkin discretizations? This would be bad and we would need to find a solution for this. It is probably only a question of time that adaptively refined meshes will be introduced for other PDE model problems (apart from IncNS with DG discretization) as well.

**Comment by nfehn** [comment]
@kronbichler, maybe you could comment on the questions raised above in the new issue #386. I believe it is better to discuss this separately.

PR #384 addresses a solution to the present issue.
