### ISSUE TITLE
Strange const_cast of const reference without reset

### ISSUE THREAD

**Issue by bugrahantemur** [exadg/exadg#446]
In `Poisson::Operator::solve`, one input parameter is `VectorType const & rhs`, but in the function body, the constness is then cast away with `const_cast` and the values in `rhs` are changed.

See:

https://github.com/exadg/exadg/blob/85e1ce3c9c678f97e6f048b47b36b105ea028202/include/exadg/poisson/spatial_discretization/operator.cpp#L513-L519

Firstly, this is dangerous and would result in undefined behavior if the passed in object `rhs` were actually `const`, which it luckily isn't in this case, hence it works.

Secondly, the values in `rhs` are not reset again, so getting a `const` reference is actually lying to the outside world. The vector `rhs` is not used elsewhere in the function, which could have somehow justified its being a `const` reference.

So I would suggest just modifying the input parameter to `VectorType & rhs` and ditch the `const_cast`.

Please correct me if I'm missing something.

**Comment by nfehn** [comment]
I agree that this is misleading. I could also live with copying the vector, because for the function `solve(dst, rhs)` I see good reasons (also for consistency with other parts of the code) to make the second argument `const`.

Apart from const-correctness from a formal software design perspective, it is also important to improve the aspect of constraints (where we should already have some open issues I think).
