### ISSUE TITLE
GlobalCoarsening Multigrid is not robust w.r.t. interior penalty parameter for quad/hex elements

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#452]
GlobalCoarsening Multigrid is not robust w.r.t. interior penalty parameter for quad/hex elements. For quad/hex, no difference is seen between Distributed/FullyDistributed triangulations.

In contrast, local smoothing MG is robust w.r.t. the interior penalty parameter for quad/hex elements.

Hence, we cannot expect robustness w.r.t. the interior penalty parameter for simplex elements, since simplex meshes have to use `MultigridVariant::GlobalCoarsening`.

I seems as if the global-coarsening transfer contains a bug for the DG->FE transfer either in deal.II or ExaDG.

The test case is poisson/sine with degree=5 and refine=2 (using a cph-MG strategy).

@peterrum @kronbichler @necioglu

**Comment by peterrum** [comment]
As promised, I took a look at

https://github.com/exadg/exadg/blob/fc2eb5e5e99b057719b01f7a9c3e37abb137cd4c/include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp#LL362C1-L362C81

But, I did not find an obvious problem there.

**Comment by kronbichler** [comment]
This is, as far as I can see, the same bug as in #453 and hopefully fixed by https://github.com/dealii/dealii/pull/15288. One might wonder why that particular bug resulted in increasing iteration counts for higher penalty parameters. The reason is that forgetting to clear the vector means that the content present at restriction gets added into the result of prolongation, so the bigger the penalty parameter, the bigger the residual, and the bigger the (wrong) contribution added to the solution after prolongation. It is surprising that the solver still converged for larger penalty parameters, because the operator is non-symmetric. For small penalty factors and in 3D, it would not matter too much because then the residual is small.

I think we should add the Poisson sine test, run with both local smoothing and global coarsening multigrid, to the tests of ExaDG, to avoid having the same problem unnoticed for so long again.

**Comment by nfehn** [comment]
I can report that global-coarsening MG now (i.e. with the changes from dealii/dealii#15288) seems to be robust w.r.t. the interior penalty parameter for quad/hex.

Hence, this issue can be closed once the PR in dealii is merged.

**Comment by nfehn** [comment]
Yes, it is around 5. So I am happy with these results.

**Comment by nfehn** [comment]
The dealii PR has been merged, so I am closing this issue.
