### ISSUE TITLE
LocalSmoothing multigrid broken for c-MG?

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#453]
I realized that for the poisson/sine test case, `LocalSmoothing` multigrid for hex elements (distributed or fully-distributed tria) requires significantly more iterations for cph-coarsening than in Table 5.3 of my thesis (https://mediatum.ub.tum.de/doc/1601025/1601025.pdf), with now around 11 iterations instead of 5 (for polynomial degrees 2-5).  Interestingly, `GlobalCoarsening` MG instead requires only around 7 iterations, which is much better but still noticably higher than 5. It is further strange that `GlobalCoarsening` performs better here for interior penalty factor tau=1, given that issue #452 reports a lack of robustness for global-coarsening MG w.r.t. the interior penalty parameter.

Iteration counts seem plausible for e.g. h-MG or p-MG with iterations around 12-14 (for polynomial degrees 2-5) in case of `LocalSmoothing` (and slightly higher around 13-15 for `GlobalCoarsening`). Also for pure h-MG, `LocalSmoothing` and `GlobalCoarsening` should actually yield the same results, right?

@peterrum @kronbichler

**Comment by peterrum** [comment]
> Also for pure h-MG, LocalSmoothing and GlobalCoarsening should actually yield the same results, right?

Both should give the same results for globally refinements (for all sequences h/p/c).

**Comment by kronbichler** [comment]
I looked into this and found a bug in deal.II: The code https://github.com/dealii/dealii/blob/2896a7e6381a97c79d9cad55ba4c2f1fbac4b05a/include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h#L2633-L2634 checks for `fine_element_is_continuous`, but then the function always adds into the `vec_fine_ptr` anyway. I think at some point we had the option to perform a `set` rather than add inside `prolongate_and_add_internal`, but that seems to be gone now.

I assume the tests in deal.II did not catch this because we typically have `use_src_inplace` for discontinuous elements. Either way, we should add a test, and I will open a PR with that change for deal.II. However, for ExaDG my concern is that we should not have arrived in this branch. We really should initialize the transfer with partitioners from the underlying `MatrixFree` objects, in order avoid copying data back and forth.

**Comment by nfehn** [comment]
local-smoothing MR with cph-coarsening still seems to require too many iterations (11 vs. 5) with the changes from https://github.com/dealii/dealii/pull/15288

**Comment by kronbichler** [comment]
Thank you for confirming. I investigated these issues together, so I missed this. Let me look into the errors (I will not get around doing it before tomorrow, I am at a conference right now).

**Comment by nfehn** [comment]
Even with the fixes from PR #464, local smoothing MG with c-transfer on the fine level requires too many iterations (11), while we should achieve around 5 optimally.

All other multigrid coarsening strategies (e.g. h, hp, ph, hpc, phc) give reasonable iteration counts. Hence, there seems to be a problem with cMG+MultigridVariant::LocalSmoothing in ExaDG.
