### ISSUE TITLE
Warning in PointwiseOutputGeneratorBase

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#502]
I get warnings that the constructor of `PointwiseOutputGeneratorBase` does not initialize all member variables. This should be fixed.

**Comment by nfehn** [comment]
I was just going through these files again. @jh66637 would you like to do this?

**Comment by jh66637** [comment]
@nfehn Sure, I can do it. Just give me a few days until I can start working on ExaDG again.

Just one question for clarification: Is it possible to initialize data members directly instead of overloading the default constructor, or is this (as I understood it by now) a design decision of ExaDG? As a matter of fact I forgot to initialize members also in another place which caused a hard to spot bug. I am in favor of only using constructors if needed to avoid bugs, code bloat (and technically the rule of five, which is not important in these kinds of classes), but I am willing to adjust to whatever is required.
