### ISSUE TITLE
Performance of JacobiPreconditioner

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#598]
I wonder if the current implementation of the Jacobi preconditioner is optimal
https://github.com/exadg/exadg/blob/51a6a7e65e81c4a3816367da24f36a4d8fc813b9/include/exadg/solvers_and_preconditioners/preconditioners/jacobi_preconditioner.h#L48-L54

If the vectors `dst`, `src` are not the same, we load the `dst` vector twice from main memory, right? Due to read-for-ownership, the data transfer would be 6 vectors (src, 2x dst, diagonal, 2x dst) in total in instead of 4 vectors in the optimal case (src, diagonal, 2x dst), right? So I am thinking of
```C++
  vmult(VectorType & dst, VectorType const & src) const final
  {
    if(dealii::PointerComparison::equal(&dst, &src))
        dst.scale(inverse_diagonal);
    else
        dst.elementwise_product(inverse_diagonal, src);
  }
```
I am not sure if deal.II provides something like `elementwise_product()`.

@kronbichler It would be great if you could comment on this.

**Comment by kronbichler** [comment]
You are right, the general approach is inefficient as the code is written and we should definitely change it. As a side note, the data transfer can be 5 vectors on some machines because `dst = src` invokes `memcpy`, which in turn uses `rep movsb` that can know the size of the transfer and thus avoid read-for-ownership. I wish this would also be done for the regular stores, because the information is there (for 512 bit writes at least).

To the solution, I suggest we write that on our own:
```
    if(dealii::PointerComparison::equal(&dst, &src))
      dst.scale(inverse_diagonal);
    else
      for (unsigned int i = 0; i < dst.local_size(); ++i)
        dst.local_element(i) = inverse_diagonal.local_element(i) * src.local_element(i);
```
or possibly with the additional annotation
```
    if(dealii::PointerComparison::equal(&dst, &src))
      dst.scale(inverse_diagonal);
    else
      {
         DEAL_II_OPENMP_SIMD_PRAGMA
         for (unsigned int i = 0; i < dst.local_size(); ++i)
            dst.local_element(i) = inverse_diagonal.local_element(i) * src.local_element(i);
        }
```
to ensure that the loop gets vectorized. We could also introduce some free functions to handle those operations. I think it would be great if we had them, because the vector interface in deal.II is a bit narrow (it is understandable from a design/interface perspective against the background of multiple vector interface, but from a performance perspective we should try to have the optimal solutions in ExaDG).

**Comment by nfehn** [comment]
Ok. I will change it right now (as described above) in ExaDG.
