### ISSUE TITLE
Not all variants of MGCoarseKrylov use projected rhs vector (with nullspace projection)

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#682]
See here https://github.com/exadg/exadg/blob/04c253618e9cca70ec839f6a57be75b839f91f00/include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h#L194-L196

Only the Trilinos ML branch below uses the vector `r`, while PETsc Boomer uses `src`, and also other preconditioners use `src`.

Do we all agree that this is not correct?

**Comment by kronbichler** [comment]
I agree, we should use `r` if we set it up. (We could think about only creating the copy `src -> r` in case the operator is singular, but that is a different issue.) The reason why this did not expose problems in the past could have been that the coarse solver should in theory have already zero mean because we impose it on the outer solver level, and for the coarse solver it should only be created in case we have roundoff errors (or possibly some non-standard transfer operators, which I don't think we have). On the other hand, the coarse solver should create a more or less precise inverse, so the null space is definitely sensitive there.
